{% set version = "2.9" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rmarkdown
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rmarkdown_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rmarkdown/rmarkdown_{{ version }}.tar.gz
  sha256: 6ce5af8b9a7c282619f74d3999d27ec4de12d3f93cde8fd12cc4c19f02ea8668

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-base64enc
    - r-evaluate >=0.13
    - r-htmltools >=0.3.5
    - r-jsonlite
    - r-knitr >=1.22
    - r-mime
    - r-stringr >=1.2.0
    - r-tinytex >=0.11
    - r-xfun
    - r-yaml >=2.1.19
  run:
    - r-base
    - r-base64enc
    - r-evaluate >=0.13
    - r-htmltools >=0.3.5
    - r-jsonlite
    - r-knitr >=1.22
    - r-mime
    - r-stringr >=1.2.0
    - r-tinytex >=0.11
    - r-xfun
    - r-yaml >=2.1.19
    - pandoc >=1.12.3,<3.0

test:
  requires:
    - xorg-libxt                             # [not win]
    - xorg-libsm                             # [not win]
  commands:
    - $R -e "library('rmarkdown')"           # [not win]
    - "\"%R%\" -e \"library('rmarkdown')\""  # [win]
    - $R -e "capabilities()" || true         # [not win]
    - $R -e "grSoftVersion()" || true        # [not win]
    - $R -e "x <- tempfile(fileext = '.Rmd'); file.create(x); rmarkdown::render(x)"  # [not win]
    - "\"%R%\" -e \"x <- tempfile(fileext = '.Rmd'); file.create(x); rmarkdown::render(x)\""  # [win]

about:
  home: https://github.com/rstudio/rmarkdown
  license: GPL-3.0-only
  summary: Convert R Markdown documents into a variety of formats.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - mdehollander
    - bsennblad
    - philip-khor

# Package: rmarkdown
# Type: Package
# Title: Dynamic Documents for R
# Version: 1.16
# Authors@R: c( person("JJ", "Allaire", role = "aut", email = "jj@rstudio.com"), person("Yihui", "Xie", role = c("aut", "cre"), email = "xie@yihui.name", comment = c(ORCID = "0000-0003-0645-5666")), person("Jonathan", "McPherson", role = "aut", email = "jonathan@rstudio.com"), person("Javier", "Luraschi", role = "aut", email = "javier@rstudio.com"), person("Kevin", "Ushey", role = "aut", email = "kevin@rstudio.com"), person("Aron", "Atkins", role = "aut", email = "aron@rstudio.com"), person("Hadley", "Wickham", role = "aut", email = "hadley@rstudio.com"), person("Joe", "Cheng", role = "aut", email = "joe@rstudio.com"), person("Winston", "Chang", role = "aut", email = "winston@rstudio.com"), person("Richard", "Iannone", role = "aut", email = "rich@rstudio.com", comment = c(ORCID = "0000-0003-3925-190X")), # # Contributors, ordered alphabetically by first name person("Atsushi", "Yasumoto", role = "ctb", comment = c(ORCID = "0000-0002-8335-495X")), person("Barret", "Schloerke", role = "ctb"), person("Christophe", "Dervieux", role = "ctb"), person("Frederik", "Aust", role = "ctb", email = "frederik.aust@uni-koeln.de", comment = c(ORCID = "0000-0003-4900-788X")), person("Jeff", "Allen", role = "ctb", email = "jeff@rstudio.com"), person("Malcolm", "Barrett", role = "ctb"), person("Rob", "Hyndman", role = "ctb", email = "Rob.Hyndman@monash.edu"), person("Romain", "Lesur", role = "ctb"), person("Roy", "Storey", role = "ctb"), person("Ruben", "Arslan", role = "ctb", email = "ruben.arslan@uni-goettingen.de"), # # Copyright holders person(family = "RStudio, Inc.", role = "cph"), person(family = "jQuery Foundation", role = "cph", comment = "jQuery library"), person(family = "jQuery contributors", role = c("ctb", "cph"), comment = "jQuery library; authors listed in inst/rmd/h/jquery-AUTHORS.txt"), person(family = "jQuery UI contributors", role = c("ctb", "cph"), comment = "jQuery UI library; authors listed in inst/rmd/h/jqueryui-AUTHORS.txt"), person("Mark", "Otto", role = "ctb", comment = "Bootstrap library"), person("Jacob", "Thornton", role = "ctb", comment = "Bootstrap library"), person(family = "Bootstrap contributors", role = "ctb", comment = "Bootstrap library"), person(family = "Twitter, Inc", role = "cph", comment = "Bootstrap library"), person("Alexander", "Farkas", role = c("ctb", "cph"), comment = "html5shiv library"), person("Scott", "Jehl", role = c("ctb", "cph"), comment = "Respond.js library"), person("Ivan", "Sagalaev", role = c("ctb", "cph"), comment = "highlight.js library"), person("Greg", "Franko", role = c("ctb", "cph"), comment = "tocify library"), person("John", "MacFarlane", role = c("ctb", "cph"), comment = "Pandoc templates"), person(family = "Google, Inc.", role = c("ctb", "cph"), comment = "ioslides library"), person("Dave", "Raggett", role = "ctb", comment = "slidy library"), person(family = "W3C", role = "cph", comment = "slidy library"), person("Dave", "Gandy", role = c("ctb", "cph"), comment = "Font-Awesome"), person("Ben", "Sperry", role = "ctb", comment = "Ionicons"), person(family = "Drifty", role = "cph", comment = "Ionicons"), person("Aidan", "Lister", role = c("ctb", "cph"),  comment = "jQuery StickyTabs"), person("Benct Philip", "Jonsson", role = c("ctb", "cph"),  comment = "pagebreak lua filter"), person("Albert", "Krewinkel", role = c("ctb", "cph"),  comment = "pagebreak lua filter") )
# Maintainer: Yihui Xie <xie@yihui.name>
# Description: Convert R Markdown documents into a variety of formats.
# Depends: R (>= 3.0)
# Imports: tools, utils, knitr (>= 1.22), yaml (>= 2.1.19), htmltools (>= 0.3.5), evaluate (>= 0.13), base64enc, jsonlite, mime, tinytex (>= 0.11), xfun, methods, stringr (>= 1.2.0)
# Suggests: shiny (>= 0.11), tufte, testthat, digest, dygraphs, tibble, fs, pkgdown, callr (>= 2.0.0)
# SystemRequirements: pandoc (>= 1.12.3) - http://pandoc.org
# URL: https://github.com/rstudio/rmarkdown
# BugReports: https://github.com/rstudio/rmarkdown/issues
# License: GPL-3
# RoxygenNote: 6.1.1
# Encoding: UTF-8
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-10-01 17:58:00 UTC; yihui
# Author: JJ Allaire [aut], Yihui Xie [aut, cre] (<https://orcid.org/0000-0003-0645-5666>), Jonathan McPherson [aut], Javier Luraschi [aut], Kevin Ushey [aut], Aron Atkins [aut], Hadley Wickham [aut], Joe Cheng [aut], Winston Chang [aut], Richard Iannone [aut] (<https://orcid.org/0000-0003-3925-190X>), Atsushi Yasumoto [ctb] (<https://orcid.org/0000-0002-8335-495X>), Barret Schloerke [ctb], Christophe Dervieux [ctb], Frederik Aust [ctb] (<https://orcid.org/0000-0003-4900-788X>), Jeff Allen [ctb], Malcolm Barrett [ctb], Rob Hyndman [ctb], Romain Lesur [ctb], Roy Storey [ctb], Ruben Arslan [ctb], RStudio, Inc. [cph], jQuery Foundation [cph] (jQuery library), jQuery contributors [ctb, cph] (jQuery library; authors listed in inst/rmd/h/jquery-AUTHORS.txt), jQuery UI contributors [ctb, cph] (jQuery UI library; authors listed in inst/rmd/h/jqueryui-AUTHORS.txt), Mark Otto [ctb] (Bootstrap library), Jacob Thornton [ctb] (Bootstrap library), Bootstrap contributors [ctb] (Bootstrap library), Twitter, Inc [cph] (Bootstrap library), Alexander Farkas [ctb, cph] (html5shiv library), Scott Jehl [ctb, cph] (Respond.js library), Ivan Sagalaev [ctb, cph] (highlight.js library), Greg Franko [ctb, cph] (tocify library), John MacFarlane [ctb, cph] (Pandoc templates), Google, Inc. [ctb, cph] (ioslides library), Dave Raggett [ctb] (slidy library), W3C [cph] (slidy library), Dave Gandy [ctb, cph] (Font-Awesome), Ben Sperry [ctb] (Ionicons), Drifty [cph] (Ionicons), Aidan Lister [ctb, cph] (jQuery StickyTabs), Benct Philip Jonsson [ctb, cph] (pagebreak lua filter), Albert Krewinkel [ctb, cph] (pagebreak lua filter)
# Repository: CRAN
# Date/Publication: 2019-10-01 19:10:09 UTC
